version: '3.7'

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - django_tutorial_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=django_tutorial_dev
      - POSTGRES_PASSWORD=django_tutorial_dev
      - POSTGRES_DB=django_tutorial_dev

volumes:
  django_tutorial_postgres:
